/* eslint-disable */
// Auto-generated from lib/taxonomy/gics-map-2023.csv — run: node scripts/generate-gics-entries.mjs

export type GicsEntry = {
  key: string;
  sectorId: string;
  sector: string;
  industryGroupId: string;
  industryGroup: string;
  industryId: string;
  industry: string;
  subIndustryId: string;
  subIndustry: string;
  subIndustryDescription: string;
};

export const GICS_ENTRIES: GicsEntry[] = [
  {
    "key": "10101010",
    "sectorId": "10",
    "sector": "Energy",
    "industryGroupId": "1010",
    "industryGroup": "Energy",
    "industryId": "101010",
    "industry": "Energy Equipment & Services",
    "subIndustryId": "10101010",
    "subIndustry": "Oil & Gas Drilling",
    "subIndustryDescription": "Drilling contractors or owners of drilling rigs that contract their services for drilling wells."
  },
  {
    "key": "10101020",
    "sectorId": "10",
    "sector": "Energy",
    "industryGroupId": "1010",
    "industryGroup": "Energy",
    "industryId": "101010",
    "industry": "Energy Equipment & Services",
    "subIndustryId": "10101020",
    "subIndustry": "Oil & Gas Equipment & Services",
    "subIndustryDescription": "Manufacturers of equipment, including drilling rigs and equipment, and providers of supplies and services to companies involved in the drilling, evaluation and completion of oil and gas wells."
  },
  {
    "key": "10102010",
    "sectorId": "10",
    "sector": "Energy",
    "industryGroupId": "1010",
    "industryGroup": "Energy",
    "industryId": "101020",
    "industry": "Oil, Gas & Consumable Fuels",
    "subIndustryId": "10102010",
    "subIndustry": "Integrated Oil & Gas",
    "subIndustryDescription": "Integrated oil companies engaged in the exploration & production of oil and gas, as well as at least one other significant activity in either refining, marketing and transportation, or chemicals."
  },
  {
    "key": "10102020",
    "sectorId": "10",
    "sector": "Energy",
    "industryGroupId": "1010",
    "industryGroup": "Energy",
    "industryId": "101020",
    "industry": "Oil, Gas & Consumable Fuels",
    "subIndustryId": "10102020",
    "subIndustry": "Oil & Gas Exploration & Production",
    "subIndustryDescription": "Companies engaged in the exploration and production of oil and gas not classified elsewhere."
  },
  {
    "key": "10102030",
    "sectorId": "10",
    "sector": "Energy",
    "industryGroupId": "1010",
    "industryGroup": "Energy",
    "industryId": "101020",
    "industry": "Oil, Gas & Consumable Fuels",
    "subIndustryId": "10102030",
    "subIndustry": "Oil & Gas Refining & Marketing",
    "subIndustryDescription": "Companies engaged in the refining and marketing of oil, gas and/or refined products not classified in the Integrated Oil & Gas or Independent Power Producers & Energy Traders Sub-Industries."
  },
  {
    "key": "10102040",
    "sectorId": "10",
    "sector": "Energy",
    "industryGroupId": "1010",
    "industryGroup": "Energy",
    "industryId": "101020",
    "industry": "Oil, Gas & Consumable Fuels",
    "subIndustryId": "10102040",
    "subIndustry": "Oil & Gas Storage & Transportation",
    "subIndustryDescription": "Companies engaged in the storage and/or transportation of oil, gas and/or refined products. Includes diversified midstream natural gas companies, oil and refined product pipelines, coal slurry pipelines and oil & gas shipping companies."
  },
  {
    "key": "10102050",
    "sectorId": "10",
    "sector": "Energy",
    "industryGroupId": "1010",
    "industryGroup": "Energy",
    "industryId": "101020",
    "industry": "Oil, Gas & Consumable Fuels",
    "subIndustryId": "10102050",
    "subIndustry": "Coal & Consumable Fuels",
    "subIndustryDescription": "Companies primarily involved in the production and mining of coal, related products and other consumable fuels related to the generation of energy.  Excludes companies primarily producing gases classified in the Industrial Gases Sub-Industry and companies primarily mining for metallurgical (coking) coal used for steel production."
  },
  {
    "key": "15101010",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151010",
    "industry": "Chemicals",
    "subIndustryId": "15101010",
    "subIndustry": "Commodity Chemicals",
    "subIndustryDescription": "Companies that primarily produce industrial chemicals and basic chemicals. Including but not limited to plastics, synthetic fibers, films, commodity-based paints & pigments, explosives and petrochemicals. Excludes chemical companies classified in the Diversified Chemicals, Fertilizers & Agricultural Chemicals, Industrial Gases, or Specialty Chemicals Sub-Industries."
  },
  {
    "key": "15101020",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151010",
    "industry": "Chemicals",
    "subIndustryId": "15101020",
    "subIndustry": "Diversified Chemicals",
    "subIndustryDescription": "Manufacturers of a diversified range of chemical products not classified in the Industrial Gases, Commodity Chemicals, Specialty Chemicals or Fertilizers & Agricultural Chemicals Sub-Industries."
  },
  {
    "key": "15101030",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151010",
    "industry": "Chemicals",
    "subIndustryId": "15101030",
    "subIndustry": "Fertilizers & Agricultural Chemicals",
    "subIndustryDescription": "Producers of fertilizers, pesticides, potash or other agriculture-related chemicals not classified elsewhere."
  },
  {
    "key": "15101040",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151010",
    "industry": "Chemicals",
    "subIndustryId": "15101040",
    "subIndustry": "Industrial Gases",
    "subIndustryDescription": "Manufacturers of industrial gases."
  },
  {
    "key": "15101050",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151010",
    "industry": "Chemicals",
    "subIndustryId": "15101050",
    "subIndustry": "Specialty Chemicals",
    "subIndustryDescription": "Companies that primarily produce high value-added chemicals used in the manufacture of a wide variety of products, including but not limited to fine chemicals, additives, advanced polymers, adhesives, sealants and specialty paints, pigments and coatings."
  },
  {
    "key": "15102010",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151020",
    "industry": "Construction Materials",
    "subIndustryId": "15102010",
    "subIndustry": "Construction Materials",
    "subIndustryDescription": "Manufacturers of construction materials including sand, clay, gypsum, lime, aggregates, cement, concrete and bricks. Other finished or semi-finished building materials are classified  in the Building Products Sub-Industry."
  },
  {
    "key": "15103010",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151030",
    "industry": "Containers & Packaging",
    "subIndustryId": "15103010",
    "subIndustry": "Metal, Glass & Plastic Containers",
    "subIndustryDescription": "Manufacturers of metal, glass or plastic containers. Includes corks and caps."
  },
  {
    "key": "15103020",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151030",
    "industry": "Containers & Packaging",
    "subIndustryId": "15103020",
    "subIndustry": "Paper & Plastic Packaging Products & Materials",
    "subIndustryDescription": "Manufacturers of paper and cardboard containers and packaging."
  },
  {
    "key": "15104010",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151040",
    "industry": "Metals & Mining",
    "subIndustryId": "15104010",
    "subIndustry": "Aluminum",
    "subIndustryDescription": "Producers of aluminum and related products, including companies that mine or process bauxite and companies that recycle aluminum to produce finished or semi-finished products. Excludes companies that primarily produce aluminum building materials classified in the Building Products Sub-Industry."
  },
  {
    "key": "15104020",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151040",
    "industry": "Metals & Mining",
    "subIndustryId": "15104020",
    "subIndustry": "Diversified Metals & Mining",
    "subIndustryDescription": "Companies engaged in the diversified production or extraction of metals and minerals not classified elsewhere. Including, but not limited to, nonferrous metal mining (except bauxite), salt and borate mining, phosphate rock mining, and diversified mining operations. Excludes iron ore mining, classified in the Steel Sub-Industry, bauxite mining, classified in the Aluminum Sub-Industry, and coal mining, classified in either the Steel or Coal & Consumable Fuels Sub-Industries."
  },
  {
    "key": "15104025",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151040",
    "industry": "Metals & Mining",
    "subIndustryId": "15104025",
    "subIndustry": "Copper",
    "subIndustryDescription": "Companies involved primarily in copper ore mining. "
  },
  {
    "key": "15104030",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151040",
    "industry": "Metals & Mining",
    "subIndustryId": "15104030",
    "subIndustry": "Gold",
    "subIndustryDescription": "Producers of gold and related products, including companies that mine or process gold and the South African finance houses which primarily invest in, but do not operate, gold mines."
  },
  {
    "key": "15104040",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151040",
    "industry": "Metals & Mining",
    "subIndustryId": "15104040",
    "subIndustry": "Precious Metals & Minerals",
    "subIndustryDescription": "Companies mining precious metals and minerals not classified in the Gold Sub-Industry. Includes companies primarily mining platinum."
  },
  {
    "key": "15104045",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151040",
    "industry": "Metals & Mining",
    "subIndustryId": "15104045",
    "subIndustry": "Silver",
    "subIndustryDescription": "Companies primarily mining silver. Excludes companies classified in the Gold or Precious Metals & Minerals Sub-Industries."
  },
  {
    "key": "15104050",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151040",
    "industry": "Metals & Mining",
    "subIndustryId": "15104050",
    "subIndustry": "Steel",
    "subIndustryDescription": "Producers of iron and steel and related products, including metallurgical (coking) coal mining used for steel production."
  },
  {
    "key": "15105010",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151050",
    "industry": "Paper & Forest Products",
    "subIndustryId": "15105010",
    "subIndustry": "Forest Products",
    "subIndustryDescription": "Manufacturers of timber and related wood products. Includes lumber for the building industry."
  },
  {
    "key": "15105020",
    "sectorId": "15",
    "sector": "Materials",
    "industryGroupId": "1510",
    "industryGroup": "Materials",
    "industryId": "151050",
    "industry": "Paper & Forest Products",
    "subIndustryId": "15105020",
    "subIndustry": "Paper Products",
    "subIndustryDescription": "Manufacturers of all grades of paper. Excludes companies specializing in paper packaging classified in the Paper & Plastic Packaging Products & Materials Sub-Industry."
  },
  {
    "key": "20101010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201010",
    "industry": "Aerospace & Defense",
    "subIndustryId": "20101010",
    "subIndustry": "Aerospace & Defense",
    "subIndustryDescription": "Manufacturers of civil or military aerospace and defense equipment, parts or products. Includes defense electronics and space equipment."
  },
  {
    "key": "20102010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201020",
    "industry": "Building Products",
    "subIndustryId": "20102010",
    "subIndustry": "Building Products",
    "subIndustryDescription": "Manufacturers of building components and home improvement products and equipment. Excludes lumber and plywood classified under Forest Products and cement and other materials classified in the Construction Materials Sub-Industry."
  },
  {
    "key": "20103010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201030",
    "industry": "Construction & Engineering",
    "subIndustryId": "20103010",
    "subIndustry": "Construction & Engineering",
    "subIndustryDescription": "Companies engaged in primarily non-residential construction. Includes civil engineering companies and large-scale contractors. Excludes companies classified in the Homebuilding Sub-Industry."
  },
  {
    "key": "20104010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201040",
    "industry": "Electrical Equipment",
    "subIndustryId": "20104010",
    "subIndustry": "Electrical Components & Equipment",
    "subIndustryDescription": "Companies that produce electric cables and wires, electrical components or equipment not classified in the Heavy Electrical Equipment Sub-Industry."
  },
  {
    "key": "20104020",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201040",
    "industry": "Electrical Equipment",
    "subIndustryId": "20104020",
    "subIndustry": "Heavy Electrical Equipment",
    "subIndustryDescription": "Manufacturers of power-generating equipment and other heavy electrical equipment, including power turbines, heavy electrical machinery intended for fixed-use and large electrical systems. Excludes cables and wires, classified in the Electrical Components & Equipment Sub-Industry."
  },
  {
    "key": "20105010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201050",
    "industry": "Industrial Conglomerates",
    "subIndustryId": "20105010",
    "subIndustry": "Industrial Conglomerates",
    "subIndustryDescription": "Diversified industrial companies with business activities in three or more sectors, none of which contributes a majority of revenues. Stakes held are predominantly of a controlling nature and stake holders maintain an operational interest in the running of the subsidiaries."
  },
  {
    "key": "20106010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201060",
    "industry": "Machinery",
    "subIndustryId": "20106010",
    "subIndustry": "Construction Machinery & Heavy Transportation Equipment",
    "subIndustryDescription": "Manufacturers of heavy duty trucks, rolling machinery, earth-moving and construction equipment, and manufacturers of related parts. Includes non-military shipbuilding."
  },
  {
    "key": "20106015",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201060",
    "industry": "Machinery",
    "subIndustryId": "20106015",
    "subIndustry": "Agricultural & Farm Machinery",
    "subIndustryDescription": "Companies manufacturing agricultural machinery, farm machinery, and their related parts. Includes machinery used for the production of crops and agricultural livestock, agricultural tractors, planting and fertilizing machinery, fertilizer and chemical application equipment, and grain dryers and blowers."
  },
  {
    "key": "20106020",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201060",
    "industry": "Machinery",
    "subIndustryId": "20106020",
    "subIndustry": "Industrial Machinery & Supplies & Components",
    "subIndustryDescription": "Manufacturers of industrial machinery and industrial components. Includes companies that manufacture presses, machine tools, compressors, pollution control equipment, elevators, escalators, insulators, pumps, roller bearings and other metal fabrications."
  },
  {
    "key": "20107010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2010",
    "industryGroup": "Capital Goods",
    "industryId": "201070",
    "industry": "Trading Companies & Distributors",
    "subIndustryId": "20107010",
    "subIndustry": "Trading Companies & Distributors",
    "subIndustryDescription": "Trading companies and other distributors of industrial equipment and products."
  },
  {
    "key": "20201010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202010",
    "industry": "Commercial Services & Supplies",
    "subIndustryId": "20201010",
    "subIndustry": "Commercial Printing",
    "subIndustryDescription": "Companies providing commercial printing services. Includes printers primarily serving the media industry."
  },
  {
    "key": "20201050",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202010",
    "industry": "Commercial Services & Supplies",
    "subIndustryId": "20201050",
    "subIndustry": "Environmental & Facilities Services",
    "subIndustryDescription": "Companies providing environmental and facilities maintenance services. Includes waste management, facilities management and pollution control services. Excludes large-scale water treatment systems classified in the Water Utilities Sub-Industry."
  },
  {
    "key": "20201060",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202010",
    "industry": "Commercial Services & Supplies",
    "subIndustryId": "20201060",
    "subIndustry": "Office Services & Supplies",
    "subIndustryDescription": "Providers of office services and manufacturers of office supplies and equipment not classified elsewhere."
  },
  {
    "key": "20201070",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202010",
    "industry": "Commercial Services & Supplies",
    "subIndustryId": "20201070",
    "subIndustry": "Diversified Support Services",
    "subIndustryDescription": "Companies primarily providing labor oriented support services to businesses and governments.  Includes commercial cleaning services, dining & catering services, equipment repair services, industrial maintenance services, industrial auctioneers, storage & warehousing, transaction services, uniform rental services, and other business support services."
  },
  {
    "key": "20201080",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202010",
    "industry": "Commercial Services & Supplies",
    "subIndustryId": "20201080",
    "subIndustry": "Security & Alarm Services",
    "subIndustryDescription": "Companies providing security and protection services to business and governments. Includes companies providing services such as correctional facilities, security & alarm services, armored transportation & guarding. Excludes companies providing security software classified under the Systems Software Sub-Industry and home security services classified under the Specialized Consumer Services Sub-Industry. Also excludes companies manufacturing security system equipment classified under the Electronic Equipment & Instruments Sub-Industry. "
  },
  {
    "key": "20202010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202020",
    "industry": "Professional Services",
    "subIndustryId": "20202010",
    "subIndustry": "Human Resource & Employment Services",
    "subIndustryDescription": "Companies providing business support services relating to human capital management. This Sub-Industry includes employment agencies, employee training, payroll processing, benefit & retirement support services, corporate & job seeker recruitment services, and online job portals generating revenue from fees or commissions for offering recruitment services to companies or job seekers."
  },
  {
    "key": "20202020",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202020",
    "industry": "Professional Services",
    "subIndustryId": "20202020",
    "subIndustry": "Research & Consulting Services",
    "subIndustryDescription": "Companies primarily providing research and consulting services to businesses and governments not classified elsewhere.  Includes companies involved in management consulting services, architectural design, business information or scientific research, marketing, and testing & certification services. Excludes companies providing information technology consulting services classified in the IT Consulting & Other Services Sub-Industry."
  },
  {
    "key": "20202030",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2020",
    "industryGroup": "Commercial  & Professional Services",
    "industryId": "202020",
    "industry": "Professional Services",
    "subIndustryId": "20202030",
    "subIndustry": "Data Processing & Outsourced Services",
    "subIndustryDescription": "Providers of commercial data processing and/or business process outsourcing services. This Sub-Industry includes companies providing services for customer experience management, back-office automation, call center management, and investor communications."
  },
  {
    "key": "20301010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203010",
    "industry": "Air Freight & Logistics",
    "subIndustryId": "20301010",
    "subIndustry": "Air Freight & Logistics",
    "subIndustryDescription": "Companies providing air freight transportation, courier and logistics services, including package and mail delivery and customs agents. Excludes those companies classified in the Passenger Airlines, Marine Transportation, Cargo Ground Transportation and Passenger Ground Transportation Sub-Industries."
  },
  {
    "key": "20302010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203020",
    "industry": "Passenger Airlines",
    "subIndustryId": "20302010",
    "subIndustry": "Passenger Airlines",
    "subIndustryDescription": "Companies providing primarily passenger air transportation."
  },
  {
    "key": "20303010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203030",
    "industry": "Marine Transportation",
    "subIndustryId": "20303010",
    "subIndustry": "Marine Transportation",
    "subIndustryDescription": "Companies providing goods or passenger maritime transportation. Excludes cruise-ships classified in the Hotels, Resorts & Cruise Lines Sub-Industry."
  },
  {
    "key": "20304010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203040",
    "industry": "Ground Transportation",
    "subIndustryId": "20304010",
    "subIndustry": "Rail Transportation",
    "subIndustryDescription": "Companies providing primarily goods and passenger rail  transportation."
  },
  {
    "key": "20304030",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203040",
    "industry": "Ground Transportation",
    "subIndustryId": "20304030",
    "subIndustry": "Cargo Ground Transportation",
    "subIndustryDescription": "Companies providing ground transportation services for goods and freight."
  },
  {
    "key": "20304040",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203040",
    "industry": "Ground Transportation",
    "subIndustryId": "20304040",
    "subIndustry": "Passenger Ground Transportation",
    "subIndustryDescription": "Companies providing passenger ground transportation and related services, including bus, taxi, vehicle rental, ride sharing and on-demand ride sharing platforms, and other passenger logistics."
  },
  {
    "key": "20305010",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203050",
    "industry": "Transportation Infrastructure",
    "subIndustryId": "20305010",
    "subIndustry": "Airport Services",
    "subIndustryDescription": "Operators of airports and companies providing related services."
  },
  {
    "key": "20305020",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203050",
    "industry": "Transportation Infrastructure",
    "subIndustryId": "20305020",
    "subIndustry": "Highways & Railtracks",
    "subIndustryDescription": "Owners and operators of roads, tunnels and railtracks."
  },
  {
    "key": "20305030",
    "sectorId": "20",
    "sector": "Industrials",
    "industryGroupId": "2030",
    "industryGroup": "Transportation",
    "industryId": "203050",
    "industry": "Transportation Infrastructure",
    "subIndustryId": "20305030",
    "subIndustry": "Marine Ports & Services",
    "subIndustryDescription": "Owners and operators of marine ports and related services."
  },
  {
    "key": "25101010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2510",
    "industryGroup": "Automobiles & Components",
    "industryId": "251010",
    "industry": "Automobile Components",
    "subIndustryId": "25101010",
    "subIndustry": "Automotive Parts & Equipment",
    "subIndustryDescription": "Manufacturers of parts and accessories for  automobiles and motorcycles. Excludes companies classified in the Tires & Rubber Sub-Industry."
  },
  {
    "key": "25101020",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2510",
    "industryGroup": "Automobiles & Components",
    "industryId": "251010",
    "industry": "Automobile Components",
    "subIndustryId": "25101020",
    "subIndustry": "Tires & Rubber",
    "subIndustryDescription": "Manufacturers of tires and rubber."
  },
  {
    "key": "25102010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2510",
    "industryGroup": "Automobiles & Components",
    "industryId": "251020",
    "industry": "Automobiles",
    "subIndustryId": "25102010",
    "subIndustry": "Automobile Manufacturers",
    "subIndustryDescription": "Companies that produce mainly passenger automobiles and light trucks. Excludes companies producing mainly motorcycles and three-wheelers classified in the Motorcycle Manufacturers Sub-Industry and heavy duty trucks classified in the Construction Machinery & Heavy Transportation Equipment Sub-Industry."
  },
  {
    "key": "25102020",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2510",
    "industryGroup": "Automobiles & Components",
    "industryId": "251020",
    "industry": "Automobiles",
    "subIndustryId": "25102020",
    "subIndustry": "Motorcycle Manufacturers",
    "subIndustryDescription": "Companies that produce motorcycles, scooters or three-wheelers. Excludes bicycles classified in the Leisure Products Sub-Industry. "
  },
  {
    "key": "25201010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252010",
    "industry": "Household Durables",
    "subIndustryId": "25201010",
    "subIndustry": "Consumer Electronics",
    "subIndustryDescription": "Manufacturers of consumer electronics products including TVs, home audio equipment, game consoles, digital cameras, and related products. Excludes personal home computer manufacturers classified in the Technology Hardware, Storage & Peripherals Sub-Industry, and electric household appliances classified in the Household Appliances Sub-Industry."
  },
  {
    "key": "25201020",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252010",
    "industry": "Household Durables",
    "subIndustryId": "25201020",
    "subIndustry": "Home Furnishings",
    "subIndustryDescription": "Manufacturers of soft home furnishings or furniture, including upholstery, carpets and wall-coverings."
  },
  {
    "key": "25201030",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252010",
    "industry": "Household Durables",
    "subIndustryId": "25201030",
    "subIndustry": "Homebuilding",
    "subIndustryDescription": "Residential construction companies. Includes manufacturers of prefabricated houses and semi-fixed manufactured homes."
  },
  {
    "key": "25201040",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252010",
    "industry": "Household Durables",
    "subIndustryId": "25201040",
    "subIndustry": "Household Appliances",
    "subIndustryDescription": "Manufacturers of electric household appliances and related products.  Includes manufacturers of power and hand tools, including garden improvement tools.  Excludes TVs and other audio and video products classified in the Consumer Electronics Sub-Industry and personal computers classified in the Technology Hardware, Storage & Peripherals Sub-Industry."
  },
  {
    "key": "25201050",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252010",
    "industry": "Household Durables",
    "subIndustryId": "25201050",
    "subIndustry": "Housewares & Specialties",
    "subIndustryDescription": "Manufacturers of durable household products, including cutlery, cookware, glassware, crystal, silverware, utensils, kitchenware and consumer specialties not classified elsewhere."
  },
  {
    "key": "25202010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252020",
    "industry": "Leisure Products",
    "subIndustryId": "25202010",
    "subIndustry": "Leisure Products",
    "subIndustryDescription": "Manufacturers of leisure products and equipment including sports equipment, bicycles and toys."
  },
  {
    "key": "25203010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252030",
    "industry": "Textiles, Apparel & Luxury Goods",
    "subIndustryId": "25203010",
    "subIndustry": "Apparel, Accessories & Luxury Goods",
    "subIndustryDescription": "Manufacturers of apparel, accessories & luxury goods. Includes companies primarily producing designer handbags, wallets, luggage, jewelry and watches. Excludes shoes classified in the Footwear Sub-Industry."
  },
  {
    "key": "25203020",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252030",
    "industry": "Textiles, Apparel & Luxury Goods",
    "subIndustryId": "25203020",
    "subIndustry": "Footwear",
    "subIndustryDescription": "Manufacturers of footwear. Includes sport and leather shoes."
  },
  {
    "key": "25203030",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2520",
    "industryGroup": "Consumer Durables & Apparel",
    "industryId": "252030",
    "industry": "Textiles, Apparel & Luxury Goods",
    "subIndustryId": "25203030",
    "subIndustry": "Textiles",
    "subIndustryDescription": "Manufacturers of textile and related products not classified in the Apparel, Accessories & Luxury Goods, Footwear or Home Furnishings Sub-Industries."
  },
  {
    "key": "25301010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2530",
    "industryGroup": "Consumer Services",
    "industryId": "253010",
    "industry": "Hotels, Restaurants & Leisure",
    "subIndustryId": "25301010",
    "subIndustry": "Casinos & Gaming",
    "subIndustryDescription": "Owners and operators of casinos and gaming facilities. Includes companies providing lottery and betting services."
  },
  {
    "key": "25301020",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2530",
    "industryGroup": "Consumer Services",
    "industryId": "253010",
    "industry": "Hotels, Restaurants & Leisure",
    "subIndustryId": "25301020",
    "subIndustry": "Hotels, Resorts & Cruise Lines",
    "subIndustryDescription": "Owners and operators of hotels, resorts and cruise-ships. Includes travel agencies, tour operators and related services not classified elsewhere . Excludes casino-hotels classified in the Casinos & Gaming Sub-Industry."
  },
  {
    "key": "25301030",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2530",
    "industryGroup": "Consumer Services",
    "industryId": "253010",
    "industry": "Hotels, Restaurants & Leisure",
    "subIndustryId": "25301030",
    "subIndustry": "Leisure Facilities",
    "subIndustryDescription": "Owners and operators of leisure facilities, including sport and fitness centers, stadiums, golf courses and amusement parks not classified in the Movies & Entertainment Sub-Industry."
  },
  {
    "key": "25301040",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2530",
    "industryGroup": "Consumer Services",
    "industryId": "253010",
    "industry": "Hotels, Restaurants & Leisure",
    "subIndustryId": "25301040",
    "subIndustry": "Restaurants",
    "subIndustryDescription": "Owners and operators of restaurants, bars, pubs, fast-food or take-out facilities. Includes companies that provide food catering services."
  },
  {
    "key": "25302010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2530",
    "industryGroup": "Consumer Services",
    "industryId": "253020",
    "industry": "Diversified Consumer Services",
    "subIndustryId": "25302010",
    "subIndustry": "Education Services",
    "subIndustryDescription": "Companies providing educational services, either on-line or through conventional teaching methods. Includes, private universities, correspondence teaching, providers of educational seminars, educational materials and technical education. Excludes companies providing employee education programs classified in the Human Resources & Employment Services Sub-Industry."
  },
  {
    "key": "25302020",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2530",
    "industryGroup": "Consumer Services",
    "industryId": "253020",
    "industry": "Diversified Consumer Services",
    "subIndustryId": "25302020",
    "subIndustry": "Specialized Consumer Services",
    "subIndustryDescription": "Companies providing consumer services not classified elsewhere.  Includes residential services, home security, legal services, personal services, renovation & interior design services, consumer auctions and wedding & funeral services."
  },
  {
    "key": "25501010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255010",
    "industry": "Distributors",
    "subIndustryId": "25501010",
    "subIndustry": "Distributors",
    "subIndustryDescription": "Distributors and wholesalers of general merchandise not classified elsewhere. Includes vehicle distributors."
  },
  {
    "key": "25503030",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255030",
    "industry": "Broadline Retail",
    "subIndustryId": "25503030",
    "subIndustry": "Broadline Retail",
    "subIndustryDescription": "Retailers offering a wide range of consumer discretionary merchandise. This Sub-Industry includes general and discount merchandise retailers, department stores and on-line retailers and marketplaces selling mostly consumer discretionary merchandise."
  },
  {
    "key": "25504010",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255040",
    "industry": "Specialty Retail",
    "subIndustryId": "25504010",
    "subIndustry": "Apparel Retail",
    "subIndustryDescription": "Retailers specialized mainly in apparel and accessories."
  },
  {
    "key": "25504020",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255040",
    "industry": "Specialty Retail",
    "subIndustryId": "25504020",
    "subIndustry": "Computer & Electronics Retail",
    "subIndustryDescription": "Owners and operators of consumer electronics, computers, video and related products retail stores."
  },
  {
    "key": "25504030",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255040",
    "industry": "Specialty Retail",
    "subIndustryId": "25504030",
    "subIndustry": "Home Improvement Retail",
    "subIndustryDescription": "Owners and operators of home and garden improvement retail stores. Includes stores offering building materials and supplies."
  },
  {
    "key": "25504040",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255040",
    "industry": "Specialty Retail",
    "subIndustryId": "25504040",
    "subIndustry": "Other Specialty Retail",
    "subIndustryDescription": "Owners and operators of specialty retail stores not classified elsewhere. Includes jewelry stores, toy stores, office supply stores, health & vision care stores, and book & entertainment stores."
  },
  {
    "key": "25504050",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255040",
    "industry": "Specialty Retail",
    "subIndustryId": "25504050",
    "subIndustry": "Automotive Retail",
    "subIndustryDescription": "Owners and operators of stores specializing in automotive retail.  Includes auto dealers, gas stations, and retailers of auto accessories, motorcycles & parts, automotive glass, and automotive equipment & parts."
  },
  {
    "key": "25504060",
    "sectorId": "25",
    "sector": "Consumer Discretionary",
    "industryGroupId": "2550",
    "industryGroup": "Consumer Discretionary Distribution & Retail ",
    "industryId": "255040",
    "industry": "Specialty Retail",
    "subIndustryId": "25504060",
    "subIndustry": "Homefurnishing Retail",
    "subIndustryDescription": "Owners and operators of furniture and home furnishings retail stores. Includes residential furniture, homefurnishings, housewares, and interior design.  Excludes home and garden improvement stores, classified in the Home Improvement Retail Sub-Industry."
  },
  {
    "key": "30101010",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3010",
    "industryGroup": "Consumer Staples Distribution & Retail",
    "industryId": "301010",
    "industry": "Consumer Staples Distribution & Retail",
    "subIndustryId": "30101010",
    "subIndustry": "Drug Retail",
    "subIndustryDescription": "Owners and operators of primarily drug retail stores and pharmacies."
  },
  {
    "key": "30101020",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3010",
    "industryGroup": "Consumer Staples Distribution & Retail",
    "industryId": "301010",
    "industry": "Consumer Staples Distribution & Retail",
    "subIndustryId": "30101020",
    "subIndustry": "Food Distributors",
    "subIndustryDescription": "Distributors of food products to other companies and not directly to the consumer."
  },
  {
    "key": "30101030",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3010",
    "industryGroup": "Consumer Staples Distribution & Retail",
    "industryId": "301010",
    "industry": "Consumer Staples Distribution & Retail",
    "subIndustryId": "30101030",
    "subIndustry": "Food Retail",
    "subIndustryDescription": "Owners and operators of primarily food retail stores."
  },
  {
    "key": "30101040",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3010",
    "industryGroup": "Consumer Staples Distribution & Retail",
    "industryId": "301010",
    "industry": "Consumer Staples Distribution & Retail",
    "subIndustryId": "30101040",
    "subIndustry": "Consumer Staples Merchandise Retail",
    "subIndustryDescription": "Retailers offering a wide range of consumer staples merchandise such as food, household, and personal care products. This Sub-Industry includes hypermarkets, super centers and other consumer staples retailers such as discount retail spaces and on-line marketplaces selling mostly consumer staples goods."
  },
  {
    "key": "30201010",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3020",
    "industryGroup": "Food, Beverage & Tobacco",
    "industryId": "302010",
    "industry": "Beverages",
    "subIndustryId": "30201010",
    "subIndustry": "Brewers",
    "subIndustryDescription": "Producers of beer and malt liquors. Includes breweries not classified in the Restaurants Sub-Industry."
  },
  {
    "key": "30201020",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3020",
    "industryGroup": "Food, Beverage & Tobacco",
    "industryId": "302010",
    "industry": "Beverages",
    "subIndustryId": "30201020",
    "subIndustry": "Distillers & Vintners",
    "subIndustryDescription": "Distillers, vintners and producers of alcoholic beverages not classified in the Brewers Sub-Industry."
  },
  {
    "key": "30201030",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3020",
    "industryGroup": "Food, Beverage & Tobacco",
    "industryId": "302010",
    "industry": "Beverages",
    "subIndustryId": "30201030",
    "subIndustry": "Soft Drinks & Non-alcoholic Beverages",
    "subIndustryDescription": "Producers of non-alcoholic beverages including mineral waters. Excludes producers of milk classified in the Packaged Foods & Meats Sub-Industry."
  },
  {
    "key": "30202010",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3020",
    "industryGroup": "Food, Beverage & Tobacco",
    "industryId": "302020",
    "industry": "Food Products",
    "subIndustryId": "30202010",
    "subIndustry": "Agricultural Products & Services",
    "subIndustryDescription": "Producers of agricultural products. Includes crop growers, owners of plantations and companies that produce and process foods but do not package and market them. Excludes companies classified in the Forest Products Sub-Industry and those that package and market the food products classified in the Packaged Foods & Meats Sub-Industry."
  },
  {
    "key": "30202030",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3020",
    "industryGroup": "Food, Beverage & Tobacco",
    "industryId": "302020",
    "industry": "Food Products",
    "subIndustryId": "30202030",
    "subIndustry": "Packaged Foods & Meats",
    "subIndustryDescription": "Producers of packaged foods including dairy products, fruit juices, meats, poultry, fish and pet foods."
  },
  {
    "key": "30203010",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3020",
    "industryGroup": "Food, Beverage & Tobacco",
    "industryId": "302030",
    "industry": "Tobacco",
    "subIndustryId": "30203010",
    "subIndustry": "Tobacco",
    "subIndustryDescription": "Manufacturers of cigarettes and other tobacco products."
  },
  {
    "key": "30301010",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3030",
    "industryGroup": "Household & Personal Products",
    "industryId": "303010",
    "industry": "Household Products",
    "subIndustryId": "30301010",
    "subIndustry": "Household Products",
    "subIndustryDescription": "Producers of non-durable household products, including detergents, soaps, diapers and other tissue and household paper products not classified in the Paper Products Sub-Industry."
  },
  {
    "key": "30302010",
    "sectorId": "30",
    "sector": "Consumer Staples",
    "industryGroupId": "3030",
    "industryGroup": "Household & Personal Products",
    "industryId": "303020",
    "industry": "Personal Care Products",
    "subIndustryId": "30302010",
    "subIndustry": "Personal Care Products",
    "subIndustryDescription": "Manufacturers of personal and beauty care products, including cosmetics and perfumes."
  },
  {
    "key": "35101010",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3510",
    "industryGroup": "Health Care Equipment & Services",
    "industryId": "351010",
    "industry": "Health Care Equipment & Supplies",
    "subIndustryId": "35101010",
    "subIndustry": "Health Care Equipment",
    "subIndustryDescription": "Manufacturers of health care equipment and devices. Includes medical instruments, drug delivery systems, cardiovascular & orthopedic devices, and diagnostic equipment."
  },
  {
    "key": "35101020",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3510",
    "industryGroup": "Health Care Equipment & Services",
    "industryId": "351010",
    "industry": "Health Care Equipment & Supplies",
    "subIndustryId": "35101020",
    "subIndustry": "Health Care Supplies",
    "subIndustryDescription": "Manufacturers of health care supplies and medical products not classified elsewhere. Includes eye care products, hospital supplies, and safety needle & syringe devices."
  },
  {
    "key": "35102010",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3510",
    "industryGroup": "Health Care Equipment & Services",
    "industryId": "351020",
    "industry": "Health Care Providers & Services",
    "subIndustryId": "35102010",
    "subIndustry": "Health Care Distributors",
    "subIndustryDescription": "Distributors and wholesalers of health care products not classified elsewhere. "
  },
  {
    "key": "35102015",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3510",
    "industryGroup": "Health Care Equipment & Services",
    "industryId": "351020",
    "industry": "Health Care Providers & Services",
    "subIndustryId": "35102015",
    "subIndustry": "Health Care Services",
    "subIndustryDescription": "Providers of patient health care services not classified elsewhere. Includes dialysis centers, lab testing services, and pharmacy management services. Also includes companies providing business support services to health care providers, such as clerical support services, collection agency services, staffing services and outsourced sales & marketing services."
  },
  {
    "key": "35102020",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3510",
    "industryGroup": "Health Care Equipment & Services",
    "industryId": "351020",
    "industry": "Health Care Providers & Services",
    "subIndustryId": "35102020",
    "subIndustry": "Health Care Facilities",
    "subIndustryDescription": "Owners and operators of health care facilities, including hospitals, nursing homes, rehabilitation centers and animal hospitals."
  },
  {
    "key": "35102030",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3510",
    "industryGroup": "Health Care Equipment & Services",
    "industryId": "351020",
    "industry": "Health Care Providers & Services",
    "subIndustryId": "35102030",
    "subIndustry": "Managed Health Care",
    "subIndustryDescription": "Owners and operators of Health Maintenance Organizations (HMOs) and other managed plans."
  },
  {
    "key": "35103010",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3510",
    "industryGroup": "Health Care Equipment & Services",
    "industryId": "351030",
    "industry": "Health Care Technology",
    "subIndustryId": "35103010",
    "subIndustry": "Health Care Technology",
    "subIndustryDescription": "Companies providing information technology services primarily to health care providers.  Includes companies providing application, systems and/or data processing software, internet-based tools, and IT consulting services to doctors, hospitals or businesses operating primarily in the Health Care Sector."
  },
  {
    "key": "35201010",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3520",
    "industryGroup": "Pharmaceuticals, Biotechnology & Life Sciences",
    "industryId": "352010",
    "industry": "Biotechnology",
    "subIndustryId": "35201010",
    "subIndustry": "Biotechnology",
    "subIndustryDescription": "Companies primarily engaged in the research, development, manufacturing and/or marketing of products based on genetic analysis and genetic engineering.  Includes companies specializing in protein-based therapeutics to treat human diseases. Excludes companies manufacturing products using biotechnology but without a health care application."
  },
  {
    "key": "35202010",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3520",
    "industryGroup": "Pharmaceuticals, Biotechnology & Life Sciences",
    "industryId": "352020",
    "industry": "Pharmaceuticals",
    "subIndustryId": "35202010",
    "subIndustry": "Pharmaceuticals",
    "subIndustryDescription": "Companies engaged in the research, development or production of pharmaceuticals. Includes veterinary drugs."
  },
  {
    "key": "35203010",
    "sectorId": "35",
    "sector": "Health Care",
    "industryGroupId": "3520",
    "industryGroup": "Pharmaceuticals, Biotechnology & Life Sciences",
    "industryId": "352030",
    "industry": "Life Sciences Tools & Services",
    "subIndustryId": "35203010",
    "subIndustry": "Life Sciences Tools & Services",
    "subIndustryDescription": "Companies enabling the drug discovery, development and production continuum by providing analytical tools, instruments, consumables & supplies, clinical trial services and contract research services. Includes firms primarily servicing the pharmaceutical and biotechnology industries."
  },
  {
    "key": "40101010",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4010",
    "industryGroup": "Banks",
    "industryId": "401010",
    "industry": "Banks",
    "subIndustryId": "40101010",
    "subIndustry": "Diversified Banks",
    "subIndustryDescription": "Large, geographically diverse banks with a national footprint whose revenues are derived primarily from conventional banking operations, have significant business activity in retail banking and small and medium corporate lending, and provide a diverse range of financial services. Excludes banks classified in the Regional Banks and Commercial & Residential Mortgage Finance Sub-Industries. Also excludes investment banks classified in the Investment Banking & Brokerage Sub-Industry."
  },
  {
    "key": "40101015",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4010",
    "industryGroup": "Banks",
    "industryId": "401010",
    "industry": "Banks",
    "subIndustryId": "40101015",
    "subIndustry": "Regional Banks",
    "subIndustryDescription": "Commercial banks, savings banks and thrifts whose business are derived primarily from conventional banking operations such as retail banking, corporate lending and originating various residential and commercial mortgage loans funded mainly through deposits. Regional banks tend to operate in limited geographic regions. Excludes companies classified in the Diversified Banks and Commercial & Residential Mortgage Finance Sub-Industries. Also excludes investment banks classified in the Investment Banking & Brokerage Sub-Industry."
  },
  {
    "key": "40201020",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402010",
    "industry": " Financial Services",
    "subIndustryId": "40201020",
    "subIndustry": "Diversified Financial Services",
    "subIndustryDescription": "Providers of a diverse range of financial services and/or with some interest in a wide range of financial services including banking, insurance and capital markets, but with no dominant business line. Excludes companies classified in the Regional Banks and Diversified Banks Sub-Industries."
  },
  {
    "key": "40201030",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402010",
    "industry": " Financial Services",
    "subIndustryId": "40201030",
    "subIndustry": "Multi-Sector Holdings",
    "subIndustryDescription": "A company with significantly diversified holdings across three or more sectors, none of which contributes a majority of profit and/or sales. Stakes held are predominantly of a non-controlling nature. Includes diversified financial companies where stakes held are of a controlling nature. Excludes other diversified companies classified in the Industrials Conglomerates Sub-Industry."
  },
  {
    "key": "40201040",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402010",
    "industry": " Financial Services",
    "subIndustryId": "40201040",
    "subIndustry": "Specialized Finance",
    "subIndustryDescription": "Providers of specialized financial services not classified elsewhere. Companies in this Sub-Industry derive a majority of revenue from one specialized line of business. Includes, but not limited to, commercial financing companies, central banks,  leasing institutions, factoring services, and specialty boutiques. Excludes companies classified in the Financial Exchanges & Data Sub-Industry."
  },
  {
    "key": "40201050",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402010",
    "industry": " Financial Services",
    "subIndustryId": "40201050",
    "subIndustry": "Commercial & Residential Mortgage Finance",
    "subIndustryDescription": "Financial companies providing commercial and residential mortgage financing and related mortgage services. This Sub-Industry includes non-deposit funded mortgage lending institutions, building societies, companies providing real estate financing products, loan servicing, mortgage broker services, and mortgage insurance. "
  },
  {
    "key": "40201060",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402010",
    "industry": " Financial Services",
    "subIndustryId": "40201060",
    "subIndustry": "Transaction & Payment Processing Services",
    "subIndustryDescription": "Providers of transaction & payment processing services and related payment services including digital/mobile payment processors, payment service providers & gateways, and digital wallet providers."
  },
  {
    "key": "40202010",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402020",
    "industry": "Consumer Finance",
    "subIndustryId": "40202010",
    "subIndustry": "Consumer Finance",
    "subIndustryDescription": "Providers of consumer finance services, including personal credit, credit cards, lease financing, travel-related money services and pawn shops. Excludes mortgage lenders classified in the Commercial & Residential Mortgage Finance Sub-Industry."
  },
  {
    "key": "40203010",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402030",
    "industry": "Capital Markets",
    "subIndustryId": "40203010",
    "subIndustry": "Asset Management & Custody Banks",
    "subIndustryDescription": "Financial institutions primarily engaged in investment management and/or related custody and securities fee-based services. Includes companies operating mutual funds, closed-end funds and unit investment trusts.  Excludes banks and other financial institutions primarily involved in commercial lending, investment banking, brokerage and other specialized financial activities. "
  },
  {
    "key": "40203020",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402030",
    "industry": "Capital Markets",
    "subIndustryId": "40203020",
    "subIndustry": "Investment Banking & Brokerage",
    "subIndustryDescription": "Financial institutions primarily engaged in investment banking & brokerage services, including equity and debt underwriting, mergers and acquisitions, securities lending and advisory services. Excludes banks and other financial institutions primarily involved in commercial lending, asset management and specialized financial activities. "
  },
  {
    "key": "40203030",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402030",
    "industry": "Capital Markets",
    "subIndustryId": "40203030",
    "subIndustry": "Diversified Capital Markets",
    "subIndustryDescription": "Financial institutions primarily engaged in diversified capital markets activities, including a significant presence in at least two of the following area: large/major corporate lending, investment banking, brokerage and asset management. Excludes less diversified companies classified in the Asset Management & Custody Banks or Investment Banking & Brokerage Sub-Industries.  Also excludes companies classified in the Banks or Insurance industry groups or the Consumer Finance Sub-Industry. "
  },
  {
    "key": "40203040",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402030",
    "industry": "Capital Markets",
    "subIndustryId": "40203040",
    "subIndustry": "Financial Exchanges & Data",
    "subIndustryDescription": "Financial exchanges for securities, commodities, derivatives and other financial instruments, and providers of financial decision support tools and products including ratings agencies."
  },
  {
    "key": "40204010",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4020",
    "industryGroup": "Financial Services ",
    "industryId": "402040",
    "industry": "Mortgage Real Estate Investment Trusts (REITs)",
    "subIndustryId": "40204010",
    "subIndustry": "Mortgage REITs",
    "subIndustryDescription": "Companies or Trusts that service, originate, purchase and/or securitize residential and/or commercial mortgage loans.  Includes trusts that invest in mortgage-backed securities and other mortgage related assets."
  },
  {
    "key": "40301010",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4030",
    "industryGroup": "Insurance",
    "industryId": "403010",
    "industry": "Insurance",
    "subIndustryId": "40301010",
    "subIndustry": "Insurance Brokers",
    "subIndustryDescription": "Insurance and reinsurance brokerage firms."
  },
  {
    "key": "40301020",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4030",
    "industryGroup": "Insurance",
    "industryId": "403010",
    "industry": "Insurance",
    "subIndustryId": "40301020",
    "subIndustry": "Life & Health Insurance",
    "subIndustryDescription": "Companies providing primarily life, disability, indemnity or supplemental health insurance. Excludes managed care companies classified in the Managed Health Care Sub-Industry."
  },
  {
    "key": "40301030",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4030",
    "industryGroup": "Insurance",
    "industryId": "403010",
    "industry": "Insurance",
    "subIndustryId": "40301030",
    "subIndustry": "Multi-line Insurance",
    "subIndustryDescription": "Insurance companies with diversified interests in life, health and property and casualty insurance."
  },
  {
    "key": "40301040",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4030",
    "industryGroup": "Insurance",
    "industryId": "403010",
    "industry": "Insurance",
    "subIndustryId": "40301040",
    "subIndustry": "Property & Casualty Insurance",
    "subIndustryDescription": "Companies providing primarily property and casualty insurance."
  },
  {
    "key": "40301050",
    "sectorId": "40",
    "sector": "Financials",
    "industryGroupId": "4030",
    "industryGroup": "Insurance",
    "industryId": "403010",
    "industry": "Insurance",
    "subIndustryId": "40301050",
    "subIndustry": "Reinsurance",
    "subIndustryDescription": "Companies providing primarily reinsurance."
  },
  {
    "key": "45102010",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4510",
    "industryGroup": "Software & Services",
    "industryId": "451020",
    "industry": "IT Services",
    "subIndustryId": "45102010",
    "subIndustry": "IT Consulting & Other Services",
    "subIndustryDescription": "Providers of information technology and systems integration services not classified in the Data Processing & Outsourced Services or Internet Software & Services Sub-Industries. Includes information technology consulting and information management services."
  },
  {
    "key": "45102030",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4510",
    "industryGroup": "Software & Services",
    "industryId": "451020",
    "industry": "IT Services",
    "subIndustryId": "45102030",
    "subIndustry": "Internet Services & Infrastructure",
    "subIndustryDescription": "Companies providing services and infrastructure for the internet industry including data centers and cloud networking and storage infrastructure. Also includes companies providing web hosting services. Excludes companies classified in the Software Industry."
  },
  {
    "key": "45103010",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4510",
    "industryGroup": "Software & Services",
    "industryId": "451030",
    "industry": "Software",
    "subIndustryId": "45103010",
    "subIndustry": "Application Software",
    "subIndustryDescription": "Companies engaged in developing and producing software designed for specialized applications for the business or consumer market. Includes enterprise and technical software, as well as cloud-based software. Excludes companies classified in the Interactive Home Entertainment Sub-Industry. Also excludes companies producing systems or database management software classified in the Systems Software Sub-Industry."
  },
  {
    "key": "45103020",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4510",
    "industryGroup": "Software & Services",
    "industryId": "451030",
    "industry": "Software",
    "subIndustryId": "45103020",
    "subIndustry": "Systems Software",
    "subIndustryDescription": "Companies engaged in developing and producing systems and database management software."
  },
  {
    "key": "45201020",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4520",
    "industryGroup": "Technology Hardware & Equipment",
    "industryId": "452010",
    "industry": "Communications Equipment",
    "subIndustryId": "45201020",
    "subIndustry": "Communications Equipment",
    "subIndustryDescription": "Manufacturers of communication equipment and products, including LANs, WANs, routers, telephones, switchboards and exchanges. Excludes cellular phone manufacturers classified in the Technology Hardware, Storage & Peripherals Sub-Industry."
  },
  {
    "key": "45202030",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4520",
    "industryGroup": "Technology Hardware & Equipment",
    "industryId": "452020",
    "industry": "Technology Hardware, Storage & Peripherals",
    "subIndustryId": "45202030",
    "subIndustry": "Technology Hardware, Storage & Peripherals",
    "subIndustryDescription": "Manufacturers of cellular phones, personal computers, servers, electronic computer components and peripherals. Includes data storage components, motherboards, audio and video cards, monitors, keyboards, printers, and other peripherals. Excludes semiconductors classified in the Semiconductors Sub-Industry."
  },
  {
    "key": "45203010",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4520",
    "industryGroup": "Technology Hardware & Equipment",
    "industryId": "452030",
    "industry": "Electronic Equipment, Instruments & Components",
    "subIndustryId": "45203010",
    "subIndustry": "Electronic Equipment & Instruments",
    "subIndustryDescription": "Manufacturers of electronic equipment and instruments including analytical, electronic test and measurement instruments, scanner/barcode products, lasers, display screens, point-of-sales machines, and security system equipment."
  },
  {
    "key": "45203015",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4520",
    "industryGroup": "Technology Hardware & Equipment",
    "industryId": "452030",
    "industry": "Electronic Equipment, Instruments & Components",
    "subIndustryId": "45203015",
    "subIndustry": "Electronic Components",
    "subIndustryDescription": "Manufacturers of electronic components. Includes electronic components, connection devices, electron tubes, electronic capacitors and resistors, electronic coil, printed circuit board, transformer and other inductors, signal processing technology/components."
  },
  {
    "key": "45203020",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4520",
    "industryGroup": "Technology Hardware & Equipment",
    "industryId": "452030",
    "industry": "Electronic Equipment, Instruments & Components",
    "subIndustryId": "45203020",
    "subIndustry": "Electronic Manufacturing Services",
    "subIndustryDescription": "Producers of electronic equipment mainly for the OEM (Original Equipment Manufacturers) markets."
  },
  {
    "key": "45203030",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4520",
    "industryGroup": "Technology Hardware & Equipment",
    "industryId": "452030",
    "industry": "Electronic Equipment, Instruments & Components",
    "subIndustryId": "45203030",
    "subIndustry": "Technology Distributors",
    "subIndustryDescription": "Distributors of technology hardware and equipment. Includes distributors of communications equipment, computers & peripherals, semiconductors, and electronic equipment and components."
  },
  {
    "key": "45301010",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4530",
    "industryGroup": "Semiconductors & Semiconductor Equipment",
    "industryId": "453010",
    "industry": "Semiconductors & Semiconductor Equipment",
    "subIndustryId": "45301010",
    "subIndustry": "Semiconductor Materials & Equipment",
    "subIndustryDescription": "Manufacturers of semiconductor equipment, including manufacturers of the raw material and equipment used in the solar power industry."
  },
  {
    "key": "45301020",
    "sectorId": "45",
    "sector": "Information Technology",
    "industryGroupId": "4530",
    "industryGroup": "Semiconductors & Semiconductor Equipment",
    "industryId": "453010",
    "industry": "Semiconductors & Semiconductor Equipment",
    "subIndustryId": "45301020",
    "subIndustry": "Semiconductors",
    "subIndustryDescription": "Manufacturers of semiconductors and related products, including manufacturers of solar modules and cells."
  },
  {
    "key": "50101010",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5010",
    "industryGroup": "Telecommunication Services",
    "industryId": "501010",
    "industry": "Diversified Telecommunication Services",
    "subIndustryId": "50101010",
    "subIndustry": "Alternative Carriers",
    "subIndustryDescription": "Providers of communications and high-density data transmission services primarily through a high bandwidth/fiber-optic cable network."
  },
  {
    "key": "50101020",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5010",
    "industryGroup": "Telecommunication Services",
    "industryId": "501010",
    "industry": "Diversified Telecommunication Services",
    "subIndustryId": "50101020",
    "subIndustry": "Integrated Telecommunication Services",
    "subIndustryDescription": "Operators of primarily fixed-line telecommunications networks and companies providing both wireless and fixed-line telecommunications services not classified elsewhere. Also includes internet service providers offering internet access to end users."
  },
  {
    "key": "50102010",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5010",
    "industryGroup": "Telecommunication Services",
    "industryId": "501020",
    "industry": "Wireless Telecommunication Services",
    "subIndustryId": "50102010",
    "subIndustry": "Wireless Telecommunication Services",
    "subIndustryDescription": "Providers of primarily cellular or wireless telecommunication services."
  },
  {
    "key": "50201010",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5020",
    "industryGroup": "Media & Entertainment",
    "industryId": "502010",
    "industry": "Media",
    "subIndustryId": "50201010",
    "subIndustry": "Advertising",
    "subIndustryDescription": "Companies providing advertising, marketing or public relations services."
  },
  {
    "key": "50201020",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5020",
    "industryGroup": "Media & Entertainment",
    "industryId": "502010",
    "industry": "Media",
    "subIndustryId": "50201020",
    "subIndustry": "Broadcasting",
    "subIndustryDescription": "Owners and operators of television or radio broadcasting systems, including programming. Includes radio and television broadcasting, radio networks, and radio stations."
  },
  {
    "key": "50201030",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5020",
    "industryGroup": "Media & Entertainment",
    "industryId": "502010",
    "industry": "Media",
    "subIndustryId": "50201030",
    "subIndustry": "Cable & Satellite",
    "subIndustryDescription": "Providers of cable or satellite television services. Includes cable networks and program distribution."
  },
  {
    "key": "50201040",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5020",
    "industryGroup": "Media & Entertainment",
    "industryId": "502010",
    "industry": "Media",
    "subIndustryId": "50201040",
    "subIndustry": "Publishing",
    "subIndustryDescription": "Publishers of newspapers, magazines and books in print or electronic formats."
  },
  {
    "key": "50202010",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5020",
    "industryGroup": "Media & Entertainment",
    "industryId": "502020",
    "industry": "Entertainment",
    "subIndustryId": "50202010",
    "subIndustry": "Movies & Entertainment",
    "subIndustryDescription": "Companies that engage in producing and selling entertainment products and services, including companies engaged in the production, distribution and screening of movies and television shows, producers and distributors of music, entertainment theaters and sports teams. Also includes companies offering and/or producing entertainment content streamed online."
  },
  {
    "key": "50202020",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5020",
    "industryGroup": "Media & Entertainment",
    "industryId": "502020",
    "industry": "Entertainment",
    "subIndustryId": "50202020",
    "subIndustry": "Interactive Home Entertainment",
    "subIndustryDescription": "Producers of interactive gaming products, including mobile gaming applications. Also includes educational software used primarily in the home. Excludes online gambling companies classified in the Casinos & Gaming Sub-Industry."
  },
  {
    "key": "50203010",
    "sectorId": "50",
    "sector": "Communication Services",
    "industryGroupId": "5020",
    "industryGroup": "Media & Entertainment",
    "industryId": "502030",
    "industry": "Interactive Media & Services",
    "subIndustryId": "50203010",
    "subIndustry": "Interactive Media & Services",
    "subIndustryDescription": "Companies engaging in content and information creation or distribution through proprietary platforms, where revenues are derived primarily through pay-per-click advertisements. Includes search engines, social media and networking platforms, online classifieds, and online review companies."
  },
  {
    "key": "55101010",
    "sectorId": "55",
    "sector": "Utilities",
    "industryGroupId": "5510",
    "industryGroup": "Utilities",
    "industryId": "551010",
    "industry": "Electric Utilities",
    "subIndustryId": "55101010",
    "subIndustry": "Electric Utilities",
    "subIndustryDescription": "Companies that produce or distribute electricity. Includes both nuclear and non-nuclear facilities."
  },
  {
    "key": "55102010",
    "sectorId": "55",
    "sector": "Utilities",
    "industryGroupId": "5510",
    "industryGroup": "Utilities",
    "industryId": "551020",
    "industry": "Gas Utilities",
    "subIndustryId": "55102010",
    "subIndustry": "Gas Utilities",
    "subIndustryDescription": "Companies whose main charter is to distribute and transmit natural and manufactured gas. Excludes companies primarily involved in gas exploration or production classified in the Oil & Gas Exploration & Production Sub-Industry. Also excludes companies engaged in the storage and/or transportation of oil, gas, and/or refined products classified in the Oil & Gas Storage & Transportation Sub-Industry."
  },
  {
    "key": "55103010",
    "sectorId": "55",
    "sector": "Utilities",
    "industryGroupId": "5510",
    "industryGroup": "Utilities",
    "industryId": "551030",
    "industry": "Multi-Utilities",
    "subIndustryId": "55103010",
    "subIndustry": "Multi-Utilities",
    "subIndustryDescription": "Utility companies with significantly diversified activities in addition to core Electric Utility, Gas Utility and/or Water Utility operations."
  },
  {
    "key": "55104010",
    "sectorId": "55",
    "sector": "Utilities",
    "industryGroupId": "5510",
    "industryGroup": "Utilities",
    "industryId": "551040",
    "industry": "Water Utilities",
    "subIndustryId": "55104010",
    "subIndustry": "Water Utilities",
    "subIndustryDescription": "Companies that purchase and redistribute water to the end-consumer. Includes large-scale water treatment systems."
  },
  {
    "key": "55105010",
    "sectorId": "55",
    "sector": "Utilities",
    "industryGroupId": "5510",
    "industryGroup": "Utilities",
    "industryId": "551050",
    "industry": "Independent Power and Renewable Electricity Producers",
    "subIndustryId": "55105010",
    "subIndustry": "Independent Power Producers & Energy Traders",
    "subIndustryDescription": "Companies that operate as Independent Power Producers (IPPs), Gas & Power Marketing & Trading Specialists and/or Integrated Energy Merchants. Excludes producers of electricity using renewable sources, such as solar power, hydropower, and wind power. Also excludes electric transmission companies and utility distribution companies classified in the Electric Utilities Sub-Industry."
  },
  {
    "key": "55105020",
    "sectorId": "55",
    "sector": "Utilities",
    "industryGroupId": "5510",
    "industryGroup": "Utilities",
    "industryId": "551050",
    "industry": "Independent Power and Renewable Electricity Producers",
    "subIndustryId": "55105020",
    "subIndustry": "Renewable Electricity ",
    "subIndustryDescription": "Companies that engage in the generation and distribution of electricity using renewable sources, including, but not limited to, companies that produce electricity using biomass, geothermal energy, solar energy, hydropower, and wind power. Excludes companies manufacturing capital equipment used to generate electricity using renewable sources, such as manufacturers of solar power systems, installers of photovoltaic cells, and companies involved in the provision of technology, components, and services mainly to this market. "
  },
  {
    "key": "60101010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601010",
    "industry": "Diversified REITs",
    "subIndustryId": "60101010",
    "subIndustry": "Diversified REITs",
    "subIndustryDescription": "A company or Trust with significantly diversified operations across two or more property types."
  },
  {
    "key": "60102510",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601025",
    "industry": "Industrial REITs",
    "subIndustryId": "60102510",
    "subIndustry": "Industrial REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of industrial properties. Includes companies operating industrial warehouses and distribution properties."
  },
  {
    "key": "60103010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601030",
    "industry": "Hotel & Resort REITs",
    "subIndustryId": "60103010",
    "subIndustry": "Hotel & Resort REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of hotel and resort properties. "
  },
  {
    "key": "60104010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601040",
    "industry": "Office REITs",
    "subIndustryId": "60104010",
    "subIndustry": "Office REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of office properties."
  },
  {
    "key": "60105010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601050",
    "industry": "Health Care REITs",
    "subIndustryId": "60105010",
    "subIndustry": "Health Care REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties serving the health care industry, including hospitals, nursing homes, and assisted living properties."
  },
  {
    "key": "60106010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601060",
    "industry": "Residential REITs",
    "subIndustryId": "60106010",
    "subIndustry": "Multi-Family Residential REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of apartments and other multi-family housing including student housing."
  },
  {
    "key": "60106020",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601060",
    "industry": "Residential REITs",
    "subIndustryId": "60106020",
    "subIndustry": "Single-Family Residential REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of single-family residential housing including manufactured homes."
  },
  {
    "key": "60107010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601070",
    "industry": "Retail REITs",
    "subIndustryId": "60107010",
    "subIndustry": "Retail REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of shopping malls, outlet malls, neighborhood and community shopping centers."
  },
  {
    "key": "60108010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601080",
    "industry": "Specialized REITs",
    "subIndustryId": "60108010",
    "subIndustry": "Other Specialized REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of properties not classified elsewhere. This Sub-Industry includes REITs that manage and own properties such as natural gas and crude oil pipelines, gas stations, fiber optic cables, prisons, automobile parking, and automobile dealerships."
  },
  {
    "key": "60108020",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601080",
    "industry": "Specialized REITs",
    "subIndustryId": "60108020",
    "subIndustry": "Self-Storage REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of self storage properties."
  },
  {
    "key": "60108030",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601080",
    "industry": "Specialized REITs",
    "subIndustryId": "60108030",
    "subIndustry": "Telecom Tower REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of telecom towers and related structures that support wireless telecommunications."
  },
  {
    "key": "60108040",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601080",
    "industry": "Specialized REITs",
    "subIndustryId": "60108040",
    "subIndustry": "Timber REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of timberland and timber-related properties."
  },
  {
    "key": "60108050",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6010",
    "industryGroup": "Equity Real Estate Investment Trusts (REITs)",
    "industryId": "601080",
    "industry": "Specialized REITs",
    "subIndustryId": "60108050",
    "subIndustry": "Data Center REITs",
    "subIndustryDescription": "Companies or Trusts engaged in the acquisition, development, ownership, leasing, management and operation of data center properties."
  },
  {
    "key": "60201010",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6020",
    "industryGroup": "Real Estate Management & Development",
    "industryId": "602010",
    "industry": "Real Estate Management & Development",
    "subIndustryId": "60201010",
    "subIndustry": "Diversified Real Estate Activities",
    "subIndustryDescription": "Companies engaged in a diverse spectrum of real estate activities including real estate development & sales, real estate management, or real estate services, but with no dominant business line."
  },
  {
    "key": "60201020",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6020",
    "industryGroup": "Real Estate Management & Development",
    "industryId": "602010",
    "industry": "Real Estate Management & Development",
    "subIndustryId": "60201020",
    "subIndustry": "Real Estate Operating Companies",
    "subIndustryDescription": "Companies engaged in operating real estate properties for the purpose of leasing & management."
  },
  {
    "key": "60201030",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6020",
    "industryGroup": "Real Estate Management & Development",
    "industryId": "602010",
    "industry": "Real Estate Management & Development",
    "subIndustryId": "60201030",
    "subIndustry": "Real Estate Development",
    "subIndustryDescription": "Companies that develop real estate and sell the properties after development. Excludes companies classified in the Homebuilding Sub-Industry."
  },
  {
    "key": "60201040",
    "sectorId": "60",
    "sector": "Real Estate",
    "industryGroupId": "6020",
    "industryGroup": "Real Estate Management & Development",
    "industryId": "602010",
    "industry": "Real Estate Management & Development",
    "subIndustryId": "60201040",
    "subIndustry": "Real Estate Services",
    "subIndustryDescription": "Real estate service providers such as real estate agents, brokers & real estate appraisers."
  }
] as const;

export const GICS_ENTRY_KEYS = GICS_ENTRIES.map((e) => e.key) as [string, ...string[]];
