export type LinkedInIndustry = {
  code: string;
  label: string;
  group: string;
};

export const LINKEDIN_INDUSTRIES: LinkedInIndustry[] = [
  { code: "accounting", label: "Accounting", group: "Finance" },
  { code: "airlines_aviation", label: "Airlines and Aviation", group: "Transportation" },
  { code: "alternative_dispute_resolution", label: "Alternative Dispute Resolution", group: "Legal" },
  { code: "alternative_medicine", label: "Alternative Medicine", group: "Healthcare" },
  { code: "animation", label: "Animation", group: "Media" },
  { code: "apparel_fashion", label: "Apparel and Fashion", group: "Retail" },
  { code: "architecture_planning", label: "Architecture and Planning", group: "Construction" },
  { code: "arts_crafts", label: "Arts and Crafts", group: "Arts" },
  { code: "automotive", label: "Automotive", group: "Manufacturing" },
  { code: "aviation_aerospace", label: "Aviation and Aerospace", group: "Manufacturing" },
  { code: "banking", label: "Banking", group: "Finance" },
  { code: "biotechnology", label: "Biotechnology", group: "Science" },
  { code: "broadcast_media", label: "Broadcast Media", group: "Media" },
  { code: "building_materials", label: "Building Materials", group: "Construction" },
  { code: "business_supplies", label: "Business Supplies and Equipment", group: "Retail" },
  { code: "capital_markets", label: "Capital Markets", group: "Finance" },
  { code: "chemicals", label: "Chemicals", group: "Manufacturing" },
  { code: "civic_social", label: "Civic and Social Organization", group: "Nonprofit" },
  { code: "civil_engineering", label: "Civil Engineering", group: "Construction" },
  { code: "commercial_real_estate", label: "Commercial Real Estate", group: "Real Estate" },
  { code: "computer_network_security", label: "Computer and Network Security", group: "Technology" },
  { code: "computer_games", label: "Computer Games", group: "Technology" },
  { code: "computer_hardware", label: "Computer Hardware", group: "Technology" },
  { code: "computer_networking", label: "Computer Networking", group: "Technology" },
  { code: "computer_software", label: "Computer Software", group: "Technology" },
  { code: "construction", label: "Construction", group: "Construction" },
  { code: "consumer_electronics", label: "Consumer Electronics", group: "Retail" },
  { code: "consumer_goods", label: "Consumer Goods", group: "Retail" },
  { code: "consumer_services", label: "Consumer Services", group: "Services" },
  { code: "cosmetics", label: "Cosmetics", group: "Retail" },
  { code: "dairy", label: "Dairy", group: "Agriculture" },
  { code: "defense_space", label: "Defense and Space", group: "Government" },
  { code: "design", label: "Design", group: "Arts" },
  { code: "education_management", label: "Education Management", group: "Education" },
  { code: "e_learning", label: "E-Learning", group: "Education" },
  { code: "electrical_manufacturing", label: "Electrical and Electronic Manufacturing", group: "Manufacturing" },
  { code: "entertainment", label: "Entertainment", group: "Media" },
  { code: "environmental_services", label: "Environmental Services", group: "Services" },
  { code: "events_services", label: "Events Services", group: "Services" },
  { code: "executive_office", label: "Executive Office", group: "Government" },
  { code: "facilities_services", label: "Facilities Services", group: "Services" },
  { code: "farming", label: "Farming", group: "Agriculture" },
  { code: "financial_services", label: "Financial Services", group: "Finance" },
  { code: "fine_art", label: "Fine Art", group: "Arts" },
  { code: "fishery", label: "Fishery", group: "Agriculture" },
  { code: "food_beverages", label: "Food and Beverages", group: "Retail" },
  { code: "food_production", label: "Food Production", group: "Manufacturing" },
  { code: "fundraising", label: "Fund-Raising", group: "Nonprofit" },
  { code: "furniture", label: "Furniture", group: "Retail" },
  { code: "gambling_casinos", label: "Gambling and Casinos", group: "Hospitality" },
  { code: "glass_ceramics", label: "Glass, Ceramics and Concrete", group: "Manufacturing" },
  { code: "government_administration", label: "Government Administration", group: "Government" },
  { code: "government_relations", label: "Government Relations", group: "Government" },
  { code: "graphic_design", label: "Graphic Design", group: "Arts" },
  { code: "health_wellness", label: "Health, Wellness and Fitness", group: "Healthcare" },
  { code: "higher_education", label: "Higher Education", group: "Education" },
  { code: "hospital_healthcare", label: "Hospital and Health Care", group: "Healthcare" },
  { code: "hospitality", label: "Hospitality", group: "Hospitality" },
  { code: "human_resources", label: "Human Resources", group: "Services" },
  { code: "import_export", label: "Import and Export", group: "Trade" },
  { code: "individual_family_services", label: "Individual and Family Services", group: "Services" },
  { code: "industrial_automation", label: "Industrial Automation", group: "Manufacturing" },
  { code: "information_services", label: "Information Services", group: "Technology" },
  { code: "information_technology", label: "Information Technology and Services", group: "Technology" },
  { code: "insurance", label: "Insurance", group: "Finance" },
  { code: "international_affairs", label: "International Affairs", group: "Government" },
  { code: "international_trade", label: "International Trade and Development", group: "Trade" },
  { code: "internet", label: "Internet", group: "Technology" },
  { code: "investment_banking", label: "Investment Banking", group: "Finance" },
  { code: "investment_management", label: "Investment Management", group: "Finance" },
  { code: "judiciary", label: "Judiciary", group: "Legal" },
  { code: "law_enforcement", label: "Law Enforcement", group: "Government" },
  { code: "law_practice", label: "Law Practice", group: "Legal" },
  { code: "legal_services", label: "Legal Services", group: "Legal" },
  { code: "legislative_office", label: "Legislative Office", group: "Government" },
  { code: "leisure_travel", label: "Leisure, Travel and Tourism", group: "Hospitality" },
  { code: "libraries", label: "Libraries", group: "Education" },
  { code: "logistics_supply_chain", label: "Logistics and Supply Chain", group: "Transportation" },
  { code: "luxury_goods", label: "Luxury Goods and Jewelry", group: "Retail" },
  { code: "machinery", label: "Machinery", group: "Manufacturing" },
  { code: "management_consulting", label: "Management Consulting", group: "Services" },
  { code: "maritime", label: "Maritime", group: "Transportation" },
  { code: "market_research", label: "Market Research", group: "Services" },
  { code: "marketing_advertising", label: "Marketing and Advertising", group: "Services" },
  { code: "mechanical_engineering", label: "Mechanical or Industrial Engineering", group: "Manufacturing" },
  { code: "media_production", label: "Media Production", group: "Media" },
  { code: "medical_devices", label: "Medical Devices", group: "Healthcare" },
  { code: "medical_practice", label: "Medical Practice", group: "Healthcare" },
  { code: "mental_health", label: "Mental Health Care", group: "Healthcare" },
  { code: "military", label: "Military", group: "Government" },
  { code: "mining_metals", label: "Mining and Metals", group: "Manufacturing" },
  { code: "motion_pictures", label: "Motion Pictures and Film", group: "Media" },
  { code: "museums_institutions", label: "Museums and Institutions", group: "Arts" },
  { code: "music", label: "Music", group: "Media" },
  { code: "nanotechnology", label: "Nanotechnology", group: "Science" },
  { code: "newspapers", label: "Newspapers", group: "Media" },
  { code: "nonprofit", label: "Nonprofit Organization Management", group: "Nonprofit" },
  { code: "oil_energy", label: "Oil and Energy", group: "Energy" },
  { code: "online_media", label: "Online Media", group: "Media" },
  { code: "outsourcing_offshoring", label: "Outsourcing and Offshoring", group: "Services" },
  { code: "package_freight", label: "Package and Freight Delivery", group: "Transportation" },
  { code: "packaging_containers", label: "Packaging and Containers", group: "Manufacturing" },
  { code: "paper_forest", label: "Paper and Forest Products", group: "Manufacturing" },
  { code: "performing_arts", label: "Performing Arts", group: "Arts" },
  { code: "pharmaceuticals", label: "Pharmaceuticals", group: "Healthcare" },
  { code: "philanthropy", label: "Philanthropy", group: "Nonprofit" },
  { code: "photography", label: "Photography", group: "Arts" },
  { code: "plastics", label: "Plastics", group: "Manufacturing" },
  { code: "political_organization", label: "Political Organization", group: "Government" },
  { code: "primary_secondary_education", label: "Primary and Secondary Education", group: "Education" },
  { code: "printing", label: "Printing", group: "Manufacturing" },
  { code: "professional_training", label: "Professional Training and Coaching", group: "Education" },
  { code: "program_development", label: "Program Development", group: "Nonprofit" },
  { code: "public_policy", label: "Public Policy", group: "Government" },
  { code: "public_relations", label: "Public Relations and Communications", group: "Services" },
  { code: "public_safety", label: "Public Safety", group: "Government" },
  { code: "publishing", label: "Publishing", group: "Media" },
  { code: "railroad", label: "Railroad Manufacture", group: "Manufacturing" },
  { code: "ranching", label: "Ranching", group: "Agriculture" },
  { code: "real_estate", label: "Real Estate", group: "Real Estate" },
  { code: "recreational_facilities", label: "Recreational Facilities and Services", group: "Hospitality" },
  { code: "religious_institutions", label: "Religious Institutions", group: "Nonprofit" },
  { code: "renewables_environment", label: "Renewables and Environment", group: "Energy" },
  { code: "research", label: "Research", group: "Science" },
  { code: "restaurants", label: "Restaurants", group: "Hospitality" },
  { code: "retail", label: "Retail", group: "Retail" },
  { code: "security_investigations", label: "Security and Investigations", group: "Services" },
  { code: "semiconductors", label: "Semiconductors", group: "Technology" },
  { code: "shipbuilding", label: "Shipbuilding", group: "Manufacturing" },
  { code: "sporting_goods", label: "Sporting Goods", group: "Retail" },
  { code: "sports", label: "Sports", group: "Entertainment" },
  { code: "staffing_recruiting", label: "Staffing and Recruiting", group: "Services" },
  { code: "supermarkets", label: "Supermarkets", group: "Retail" },
  { code: "telecommunications", label: "Telecommunications", group: "Technology" },
  { code: "textiles", label: "Textiles", group: "Manufacturing" },
  { code: "think_tanks", label: "Think Tanks", group: "Government" },
  { code: "tobacco", label: "Tobacco", group: "Manufacturing" },
  { code: "translation", label: "Translation and Localization", group: "Services" },
  { code: "transportation", label: "Transportation/Trucking/Railroad", group: "Transportation" },
  { code: "utilities", label: "Utilities", group: "Energy" },
  { code: "venture_capital", label: "Venture Capital and Private Equity", group: "Finance" },
  { code: "veterinary", label: "Veterinary", group: "Healthcare" },
  { code: "warehousing", label: "Warehousing", group: "Transportation" },
  { code: "wholesale", label: "Wholesale", group: "Trade" },
  { code: "wine_spirits", label: "Wine and Spirits", group: "Retail" },
  { code: "wireless", label: "Wireless", group: "Technology" },
  { code: "writing_editing", label: "Writing and Editing", group: "Media" },
  { code: "other", label: "Other", group: "Other" },
];

export const LINKEDIN_INDUSTRY_CODES = LINKEDIN_INDUSTRIES.map(
  (i) => i.code
) as [string, ...string[]];

export function labelFor(code: string): string {
  return LINKEDIN_INDUSTRIES.find((i) => i.code === code)?.label ?? code;
}
